image: Visual Studio 2017
init:
  - git config --global core.autocrlf true
assembly_info:
  patch: false
configuration:
  - Debug
build_script:
  - ps: choco install dotnetcore-sdk --no-progress --confirm --version 2.1.401
  - ps: ./build.ps1
test: off
skip_tags: true
