apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webnotifier-v1
  namespace: kafka
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webnotifier
        version: v1
    spec:
      containers:
      - name: webnotifier
        image: vndg/webnotifier:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"