apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-commander-v1
  namespace: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-commander
        version: v1
    spec:
      containers:
      - name: redis-commander
        image: rediscommander/redis-commander
        imagePullPolicy: IfNotPresent
        env:
        - name: REDIS_HOSTS
          value: k8s:redis-master:6379:0:letmein
        ports:
        - name: redis-commander
          containerPort: 8081