apiVersion: v1
kind: Service
metadata:
  name: redis-commander
  namespace: redis
  labels:
    app: redis-commander
spec:
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    nodePort: 30010
    name: redis-commander
  type: NodePort
  selector:
    app: redis-commander