apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka-server-v1
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-server
  template:
    metadata:
      labels:
        app: kafka-server
        version: v1
    spec:
      terminationGracePeriodSeconds: 10
      hostNetwork: true
      containers:
      - name: kafka-server
        image: spotify/kafka
        ports:
        - name: kafka
          containerPort: 9092
          hostPort: 9092
        - name: zookeeper
          containerPort: 2181
          hostPort: 2181
        env:
        - name: ADVERTISED_HOST
          value: "127.0.0.1"
        - name: ADVERTISED_PORT
          value: "9092"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-server
  namespace: kafka
  labels:
    app: kafka-server
spec:
  selector:
    app: kafka-server
  ports:
  - name: kafka
    protocol: TCP
    port: 9092
    targetPort: 9092
  - name: zookeeper
    protocol: TCP
    port: 2181
    targetPort: 2181
  