apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka-manager-v1
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-manager
  template:
    metadata:
      labels:
        app: kafka-manager
        version: v1
    spec:
      containers:
      - name: kafka-manager
        image: solsson/kafka-manager@sha256:28b1a0b355f3972a9e3b5ac82abcbfee9a72b66a2bfe86094f6ea2caad9ce3a7
        ports:
        - containerPort: 80
        env:
        - name: ZK_HOSTS
          value: "kafka-cp-zookeeper.kafka:2181"
        command:
        - ./bin/kafka-manager
        - -Dhttp.port=80
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-manager
  namespace: kafka
  labels:
    app: kafka-manager
spec:
  selector:
    app: kafka-manager
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 80
  type: LoadBalancer