apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka-topics-ui-v1
  namespace: kafka
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-topics-ui
        version: v1
    spec:
      containers:
      - name: kafka-topics-ui
        image: landoop/kafka-topics-ui:0.9.4
        imagePullPolicy: IfNotPresent
        env:
        - name: ACCESS_CONTROL_ALLOW_ORIGIN_DEFAULT
          value: "*"
        - name: ACCESS_CONTROL_ALLOW_METHODS_DEFAULT
          value: "GET,POST,PUT,DELETE,OPTIONS"
        - name: ACCESS_CONTROL_ALLOW_ORIGIN
          value: "*"
        - name: ACCESS_CONTROL_ALLOW_METHODS
          value: "GET,POST,PUT,DELETE,OPTIONS"
        - name: KAFKA_REST_BOOTSTRAP_SERVERS
          value: "PLAINTEXT://kafka-cp-kafka:9092"
        - name: KAFKA_REST_PROXY_URL
          value: http://kafka-cp-kafka-rest:8082
        - name: SCHEMAREGISTRY_UI_URL
          value: http://kafka-cp-schema-registry:8081
        - name: PROXY
          value: "true"
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-topics-ui
  namespace: kafka
  labels:
    app: kafka-topics-ui
spec:
  ports:
  - port: 8000
    targetPort: redis-commander
    protocol: TCP
    name: http
  type: LoadBalancer
  selector:
    app: kafka-topics-ui