apiVersion: v1
kind: Pod
metadata:
  name: kafka-connect-ui
  namespace: default
spec:
  containers:
  - name: kafka-connect-ui
    image: landoop/kafka-connect-ui
    env:
    - name: CONNECT_URL
      value: kafka:9092
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-connect-ui
  namespace: default
  labels:
    app: kafka-connect-ui
spec:
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 32767
    protocol: TCP
    name: http
  type: NodePort
  selector:
    app: kafka-connect-ui