apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: signalrnotifier-v1
  namespace: netcorekit
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: signalrnotifier
        version: v1
    spec:
      containers:
      - name: signalrnotifier
        image: vndg/signalrnotifier:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: Hosts__BasePath
          value: /
        - name: Kafka__FQDN
          value: "kafka-cp-kafka.kafka:9092"
        - name: Redis__FQDN
          value: "redis-master.redis:6379"
        - name: Redis__Password
          valueFrom:
            secretKeyRef:
              name: signalrnotifier-secrets
              key: RedisPassword
        ports:
        - containerPort: 80
