apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: todolist-v1
  namespace: netcorekit
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: todolist
        version: v1
    spec:
      containers:
      - name: todolist
        image: vndg/todoapi:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: Hosts__BasePath
          value: /
        - name: MySqlDb__FQDN
          value: "mysql.netcorekit:3306"
        - name: MySqlDb__Password
          value: "P@ssw0rd"
        - name: Kafka__FQDN
          value: "kafka-cp-kafka.kafka:9092"
        - name: Redis__FQDN
          value: "redis-master.redis:6379"
        - name: Redis__Password
          value: "letmein"
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
