apiVersion: v1
kind: Service
metadata:
  name: todolist
  namespace: default
  labels:
    app: todolist
spec:
  ports:
  - port: 80
    targetPort: 5001
    nodePort: 32222
    protocol: TCP
    name: http
  type: NodePort
  selector:
    app: todolist
---
