apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: todolist-v1
  namespace: kafka
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: todolist
        version: v1
    spec:
      containers:
      - name: todolist
        image: vndg/todoapi:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: Hosts__BasePath
          value: /
        - name: EventBus__Brokers
          value: kafka-server:9092
        ports:
        - containerPort: 5001
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5001
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
