apiVersion: v1
kind: Service
metadata:
  name: todolistdb
  namespace: default
  labels:
    app: todolistdb
spec:
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
    nodePort: 32223
  type: NodePort
  selector:
    app: todolistdb
---
