apiVersion: v1
kind: Service
metadata:
  name: todolist
  namespace: kafka
  labels:
    app: todolist
spec:
  ports:
  - port: 32501
    targetPort: 5001
    nodePort: 32501
    protocol: TCP
    name: http
  type: LoadBalancer
  selector:
    app: todolist