apiVersion: v1
kind: Service
metadata:
  name: exchange
  namespace: netcorekit
  labels:
    app: exchange
spec:
  ports:
  - name: grpc
    port: 5000
    targetPort: 5000
  type: ClusterIP
  selector:
    app: exchange
