apiVersion: v1
kind: Service
metadata:
  name: exchange
  namespace: netcorekit
  labels:
    app: exchange
spec:
  ports:
  - port: 32502
    targetPort: 5000
    nodePort: 32502
    protocol: TCP
    name: http
  type: NodePort
  selector:
    app: exchange
